title: VectorSurv
description: Vectorborne Disease Surveillance System
google_analytics: UA-112879359-3

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
  - scope:
      path: _posts
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - .gitignore
  - .jekyll-cache
  - CNAME
